{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'papermill'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-9f60a445c2e0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mmultiprocessing\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPool\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mpapermill\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpm\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpathlib\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPath\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mwarnings\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'papermill'"
     ]
    }
   ],
   "source": [
    "from multiprocessing import Pool\n",
    "import os\n",
    "import papermill as pm\n",
    "from pathlib import Path\n",
    "import warnings\n",
    "warnings.simplefilter(action='ignore', category=FutureWarning)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Path' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-b72e4585c092>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mrois\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mfor\u001b[0m \u001b[0mfile\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mPath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'../data'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0miterdir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0;34m'covid_timeseries'\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m         \u001b[0mroi\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'_'\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msplit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'.'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msplit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'_'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m         \u001b[0mrois\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mroi\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'Path' is not defined"
     ]
    }
   ],
   "source": [
    "rois = []\n",
    "for file in Path('../data').iterdir():\n",
    "    if 'covid_timeseries' in str(file):\n",
    "        roi = '_'.join(file.name.split('.')[0].split('_')[2:])\n",
    "        rois.append(roi)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def execute(roi):\n",
    "    os.makedirs('fits', exist_ok=True)\n",
    "    try:\n",
    "        pm.execute_notebook(\n",
    "           'MBS_epidemic_ccclinearrd_gerkin_beta.ipynb',\n",
    "           'fits/MBS_epidemic_ccclinearrd_gerkin_beta_%s.ipynb' % roi,\n",
    "           parameters=dict(roi=roi),\n",
    "           nest_asyncio=True)\n",
    "    except pm.PapermillExecutionError as e:\n",
    "        return str(e)\n",
    "    return ''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bacda9024809419cb64d9428f62f9b21",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b97afc118f6549eab0a8b13bb8f44732",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bda72d1ec609401399c7587ec5182489",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "8338f02b35714de095f0a466e246fd20",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2c820015c73f434a8832f9abceb7f857",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b5051eabacb640d498d4bb0e05de4180",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6d47d61627104bad94cb282ea8dd713d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "be7e77e3894e4df39256c5d8c5dd9106",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2d4b9cc2aa9249adb68d28226323f364",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0ed618ec9f9d4636bb6972becc7b238c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "21e04e1c20ff496d898c7c11927766d9",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e0d5d9f68a2345e29d56ce8b7a1f33f6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9c828d3cc9be49e4afd5a1e8e52810c2",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2128b83dccc548b8be4c180fb0b4943c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "aea8e33226254b4fb54534ef8cced99b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "01d79f6b5e8f48e886e2146d6d6cb58e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "da80672091d74c5fa1451956e371eb19",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "886d42ad0aa54fd79789c56df3e94363",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ace56516bc6f44d2a5df2d1de8532db6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, description='Executing', max=25, style=ProgressStyle(description_width='in…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "pool = Pool(processes=20)\n",
    "jobs = {roi: pool.apply_async(execute, [roi]) for roi in rois}\n",
    "results = {roi: jobs[roi].get() for roi in rois}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "US_OK\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Germany\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_GU\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_VI\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_VT\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_WY\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_ND\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_SD\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_WV\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_MT\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_AK\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_KY\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Belgium\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "France\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_ME\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_MN\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Switzerland\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_NY\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_DE\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_TN\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_TX\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_NM\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_HI\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_RI\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_NH\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Iran\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_DC\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Italy\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "United Kingdom\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_IA\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_NJ\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Netherlands\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_MD\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_AR\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Spain\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Korea, South\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "Turkey\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "China\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n",
      "US_MI\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "Exception encountered at \"In [12]\":\n",
      "---------------------------------------------------------------------------\n",
      "AttributeError                            Traceback (most recent call last)\n",
      "<ipython-input-12-b374f4dce4eb> in <module>\n",
      "     10     try:\n",
      "     11         fit = stanrunmodel.sampling(data=stan_data, init=init_fun, control=control, chains = n_chains,\n",
      "---> 12                                     chain_id=np.arange(n_chains), warmup=n_warmups, iter=n_iter, thin=n_thin, seed=13219)\n",
      "     13     except RuntimeError:\n",
      "     14         curr_try += 1\n",
      "\n",
      "/opt/conda/lib/python3.7/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)\n",
      "    670 \n",
      "    671         seed = pystan.misc._check_seed(seed)\n",
      "--> 672         fit = self.fit_class(data, seed)\n",
      "    673 \n",
      "    674         m_pars = fit._get_param_names()\n",
      "\n",
      "AttributeError: 'StanModel' object has no attribute 'fit_class'\n",
      "\n",
      "===========================\n"
     ]
    }
   ],
   "source": [
    "for roi in rois:\n",
    "    result = results[roi]\n",
    "    if result: # If there was an error:\n",
    "        print(roi)\n",
    "        print(result)\n",
    "        print(\"===========================\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#try:\n",
    "#    result = pm.execute_notebook(\n",
    "#       'dummy.ipynb',\n",
    "#       'dummy-2.ipynb',\n",
    "#       parameters=dict(roi='hethhh'),\n",
    "#       nest_asyncio=True)\n",
    "#except pm.PapermillExecutionError:\n",
    "#    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
